import {
  destinationCatalogSchema,
  type DestinationCatalogEntry,
  type DestinationType,
} from '@buzzytrip/contracts';

function india(
  slug: string,
  name: string,
  stateOrRegion: string,
  destinationType: DestinationType,
  aliases: string[] = [],
): DestinationCatalogEntry {
  return {
    aliases,
    countryCode: 'IN',
    countryName: 'India',
    destinationType,
    name,
    scope: 'india',
    slug,
    stateOrRegion,
  };
}

function international(
  slug: string,
  name: string,
  countryCode: string,
  countryName: string,
  stateOrRegion: string | null,
  destinationType: DestinationType,
  aliases: string[] = [],
): DestinationCatalogEntry {
  return {
    aliases,
    countryCode,
    countryName,
    destinationType,
    name,
    scope: 'international',
    slug,
    stateOrRegion,
  };
}

const indiaDestinations: DestinationCatalogEntry[] = [
  india('agra', 'Agra', 'Uttar Pradesh', 'heritage'),
  india('ahmedabad', 'Ahmedabad', 'Gujarat', 'city'),
  india('ajmer', 'Ajmer', 'Rajasthan', 'heritage'),
  india('alappuzha', 'Alappuzha', 'Kerala', 'coast', ['alleppey']),
  india('amritsar', 'Amritsar', 'Punjab', 'heritage'),
  india(
    'andaman-and-nicobar-islands',
    'Andaman and Nicobar Islands',
    'Andaman and Nicobar Islands',
    'island',
    ['andaman islands'],
  ),
  india('auli', 'Auli', 'Uttarakhand', 'mountains'),
  india('bengaluru', 'Bengaluru', 'Karnataka', 'city', ['bangalore']),
  india('bhopal', 'Bhopal', 'Madhya Pradesh', 'city'),
  india('bhubaneswar', 'Bhubaneswar', 'Odisha', 'city'),
  india('chandigarh', 'Chandigarh', 'Chandigarh', 'city'),
  india('chennai', 'Chennai', 'Tamil Nadu', 'city', ['madras']),
  india('coorg', 'Coorg', 'Karnataka', 'countryside', ['kodagu']),
  india('darjeeling', 'Darjeeling', 'West Bengal', 'mountains'),
  india('dehradun', 'Dehradun', 'Uttarakhand', 'city'),
  india('delhi', 'Delhi', 'Delhi', 'city', ['new delhi']),
  india('dharamshala', 'Dharamshala', 'Himachal Pradesh', 'mountains', [
    'dharamsala',
    'mcleod ganj',
  ]),
  india('gangtok', 'Gangtok', 'Sikkim', 'mountains'),
  india('goa', 'Goa', 'Goa', 'coast'),
  india('gokarna', 'Gokarna', 'Karnataka', 'coast'),
  india('guwahati', 'Guwahati', 'Assam', 'city'),
  india('hampi', 'Hampi', 'Karnataka', 'heritage'),
  india('hyderabad', 'Hyderabad', 'Telangana', 'city'),
  india('jaipur', 'Jaipur', 'Rajasthan', 'heritage', ['pink city']),
  india('jaisalmer', 'Jaisalmer', 'Rajasthan', 'desert', ['golden city']),
  india('jammu', 'Jammu', 'Jammu and Kashmir', 'city'),
  india('jodhpur', 'Jodhpur', 'Rajasthan', 'heritage', ['blue city']),
  india('kanyakumari', 'Kanyakumari', 'Tamil Nadu', 'coast', ['cape comorin']),
  india('kochi', 'Kochi', 'Kerala', 'coast', ['cochin']),
  india('kolkata', 'Kolkata', 'West Bengal', 'city', ['calcutta']),
  india('ladakh', 'Ladakh', 'Ladakh', 'mountains'),
  india('lakshadweep', 'Lakshadweep', 'Lakshadweep', 'island'),
  india('lonavala', 'Lonavala', 'Maharashtra', 'mountains'),
  india('lucknow', 'Lucknow', 'Uttar Pradesh', 'heritage'),
  india('manali', 'Manali', 'Himachal Pradesh', 'mountains'),
  india('matheran', 'Matheran', 'Maharashtra', 'mountains'),
  india('meghalaya', 'Meghalaya', 'Meghalaya', 'nature'),
  india('mumbai', 'Mumbai', 'Maharashtra', 'city', ['bombay']),
  india('munnar', 'Munnar', 'Kerala', 'mountains'),
  india('mussoorie', 'Mussoorie', 'Uttarakhand', 'mountains'),
  india('mysuru', 'Mysuru', 'Karnataka', 'heritage', ['mysore']),
  india('nainital', 'Nainital', 'Uttarakhand', 'mountains'),
  india('nashik', 'Nashik', 'Maharashtra', 'city', ['nasik']),
  india('ooty', 'Ooty', 'Tamil Nadu', 'mountains', ['udhagamandalam']),
  india('puducherry', 'Puducherry', 'Puducherry', 'coast', ['pondicherry']),
  india('puri', 'Puri', 'Odisha', 'coast'),
  india('rameswaram', 'Rameswaram', 'Tamil Nadu', 'heritage', ['rameshwaram']),
  india('rishikesh', 'Rishikesh', 'Uttarakhand', 'nature'),
  india('shillong', 'Shillong', 'Meghalaya', 'mountains'),
  india('shimla', 'Shimla', 'Himachal Pradesh', 'mountains', ['simla']),
  india('srinagar', 'Srinagar', 'Jammu and Kashmir', 'nature'),
  india('udaipur', 'Udaipur', 'Rajasthan', 'heritage', ['city of lakes']),
  india('varanasi', 'Varanasi', 'Uttar Pradesh', 'heritage', ['banaras', 'benares', 'kashi']),
  india('wayanad', 'Wayanad', 'Kerala', 'nature'),
  india('khajuraho', 'Khajuraho', 'Madhya Pradesh', 'heritage'),
  india('kaziranga-national-park', 'Kaziranga National Park', 'Assam', 'wildlife', ['kaziranga']),
  india('jim-corbett-national-park', 'Jim Corbett National Park', 'Uttarakhand', 'wildlife', [
    'corbett',
    'corbett national park',
  ]),
  india('ranthambore-national-park', 'Ranthambore National Park', 'Rajasthan', 'wildlife', [
    'ranthambore',
  ]),
  india('kutch', 'Kutch', 'Gujarat', 'desert', ['rann of kutch']),
  india('ziro-valley', 'Ziro Valley', 'Arunachal Pradesh', 'countryside', ['ziro']),
  india('kerala', 'Kerala', 'Kerala', 'region'),
  india('rajasthan', 'Rajasthan', 'Rajasthan', 'region'),
  india('sikkim', 'Sikkim', 'Sikkim', 'mountains'),
  india('himachal-pradesh', 'Himachal Pradesh', 'Himachal Pradesh', 'mountains'),
  india('uttarakhand', 'Uttarakhand', 'Uttarakhand', 'mountains', ['uttaranchal']),
  india('madhya-pradesh', 'Madhya Pradesh', 'Madhya Pradesh', 'region'),
  india('tamil-nadu', 'Tamil Nadu', 'Tamil Nadu', 'region'),
  india('karnataka', 'Karnataka', 'Karnataka', 'region'),
  india('assam', 'Assam', 'Assam', 'nature'),
  india('ayodhya', 'Ayodhya', 'Uttar Pradesh', 'heritage', ['ayodhya dham']),
  india('mathura-and-vrindavan', 'Mathura and Vrindavan', 'Uttar Pradesh', 'heritage', [
    'mathura',
    'mathura vrindavan',
    'vrindavan',
  ]),
  india('mahabaleshwar', 'Mahabaleshwar', 'Maharashtra', 'mountains'),
  india('mount-abu', 'Mount Abu', 'Rajasthan', 'mountains'),
  india('spiti-valley', 'Spiti Valley', 'Himachal Pradesh', 'mountains', ['spiti']),
  india('valley-of-flowers', 'Valley of Flowers', 'Uttarakhand', 'nature', [
    'valley of flowers national park',
  ]),
];

const internationalDestinations: DestinationCatalogEntry[] = [
  international('amsterdam', 'Amsterdam', 'NL', 'Netherlands', 'North Holland', 'city'),
  international('athens', 'Athens', 'GR', 'Greece', 'Attica', 'heritage'),
  international('bali', 'Bali', 'ID', 'Indonesia', 'Bali', 'island', ['bali indonesia']),
  international('bangkok', 'Bangkok', 'TH', 'Thailand', 'Bangkok', 'city'),
  international('barcelona', 'Barcelona', 'ES', 'Spain', 'Catalonia', 'city'),
  international('beijing', 'Beijing', 'CN', 'China', 'Beijing', 'city'),
  international('berlin', 'Berlin', 'DE', 'Germany', 'Berlin', 'city'),
  international('bora-bora', 'Bora Bora', 'PF', 'French Polynesia', 'Society Islands', 'island'),
  international('budapest', 'Budapest', 'HU', 'Hungary', 'Central Hungary', 'city'),
  international('cairo', 'Cairo', 'EG', 'Egypt', 'Cairo', 'city'),
  international('cape-town', 'Cape Town', 'ZA', 'South Africa', 'Western Cape', 'coast', [
    'capetown',
  ]),
  international('cappadocia', 'Cappadocia', 'TR', 'Türkiye', 'Central Anatolia', 'region', [
    'kapadokya',
  ]),
  international('chiang-mai', 'Chiang Mai', 'TH', 'Thailand', 'Chiang Mai', 'city'),
  international('copenhagen', 'Copenhagen', 'DK', 'Denmark', 'Capital Region', 'city'),
  international('dubai', 'Dubai', 'AE', 'United Arab Emirates', 'Dubai', 'city'),
  international('dubrovnik', 'Dubrovnik', 'HR', 'Croatia', 'Dalmatia', 'coast'),
  international('edinburgh', 'Edinburgh', 'GB', 'United Kingdom', 'Scotland', 'heritage'),
  international('florence', 'Florence', 'IT', 'Italy', 'Tuscany', 'heritage', ['firenze']),
  international('gold-coast', 'Gold Coast', 'AU', 'Australia', 'Queensland', 'coast'),
  international('hanoi', 'Hanoi', 'VN', 'Vietnam', 'Red River Delta', 'city'),
  international('hong-kong', 'Hong Kong', 'HK', 'Hong Kong', null, 'city'),
  international('istanbul', 'Istanbul', 'TR', 'Türkiye', 'Marmara', 'heritage'),
  international('kyoto', 'Kyoto', 'JP', 'Japan', 'Kansai', 'heritage'),
  international('lisbon', 'Lisbon', 'PT', 'Portugal', 'Lisbon District', 'city'),
  international('london', 'London', 'GB', 'United Kingdom', 'England', 'city'),
  international('los-angeles', 'Los Angeles', 'US', 'United States', 'California', 'city'),
  international('lucerne', 'Lucerne', 'CH', 'Switzerland', 'Lucerne', 'city', ['luzern']),
  international('madrid', 'Madrid', 'ES', 'Spain', 'Community of Madrid', 'city'),
  international('maldives', 'Maldives', 'MV', 'Maldives', null, 'country'),
  international('mauritius', 'Mauritius', 'MU', 'Mauritius', null, 'country'),
  international('melbourne', 'Melbourne', 'AU', 'Australia', 'Victoria', 'city'),
  international('mexico-city', 'Mexico City', 'MX', 'Mexico', 'Mexico City', 'city', [
    'ciudad de mexico',
  ]),
  international('milan', 'Milan', 'IT', 'Italy', 'Lombardy', 'city', ['milano']),
  international('new-york-city', 'New York City', 'US', 'United States', 'New York', 'city', [
    'new york',
    'nyc',
  ]),
  international('osaka', 'Osaka', 'JP', 'Japan', 'Kansai', 'city'),
  international('paris', 'Paris', 'FR', 'France', 'Île-de-France', 'city'),
  international('phuket', 'Phuket', 'TH', 'Thailand', 'Phuket', 'island'),
  international('prague', 'Prague', 'CZ', 'Czechia', 'Prague', 'heritage', ['praha']),
  international('queenstown', 'Queenstown', 'NZ', 'New Zealand', 'Otago', 'mountains'),
  international('reykjavik', 'Reykjavik', 'IS', 'Iceland', 'Capital Region', 'city'),
  international('rome', 'Rome', 'IT', 'Italy', 'Lazio', 'heritage', ['roma']),
  international('santorini', 'Santorini', 'GR', 'Greece', 'South Aegean', 'island', ['thira']),
  international('seoul', 'Seoul', 'KR', 'South Korea', 'Seoul', 'city'),
  international('singapore', 'Singapore', 'SG', 'Singapore', null, 'country'),
  international('sydney', 'Sydney', 'AU', 'Australia', 'New South Wales', 'city'),
  international('tokyo', 'Tokyo', 'JP', 'Japan', 'Kanto', 'city'),
  international('toronto', 'Toronto', 'CA', 'Canada', 'Ontario', 'city'),
  international('venice', 'Venice', 'IT', 'Italy', 'Veneto', 'heritage', ['venezia']),
  international('vienna', 'Vienna', 'AT', 'Austria', 'Vienna', 'city', ['wien']),
  international('zurich', 'Zurich', 'CH', 'Switzerland', 'Zurich', 'city'),
  international('abu-dhabi', 'Abu Dhabi', 'AE', 'United Arab Emirates', 'Abu Dhabi', 'city'),
  international('almaty', 'Almaty', 'KZ', 'Kazakhstan', 'Almaty', 'city'),
  international('auckland', 'Auckland', 'NZ', 'New Zealand', 'Auckland', 'city'),
  international('baku', 'Baku', 'AZ', 'Azerbaijan', 'Absheron', 'city'),
  international('bhutan', 'Bhutan', 'BT', 'Bhutan', null, 'country'),
  international('brussels', 'Brussels', 'BE', 'Belgium', 'Brussels-Capital', 'city'),
  international('buenos-aires', 'Buenos Aires', 'AR', 'Argentina', 'Buenos Aires', 'city'),
  international('da-nang', 'Da Nang', 'VN', 'Vietnam', 'Central Vietnam', 'coast', ['danang']),
  international('doha', 'Doha', 'QA', 'Qatar', 'Doha', 'city'),
  international('fiji', 'Fiji', 'FJ', 'Fiji', null, 'country'),
  international('geneva', 'Geneva', 'CH', 'Switzerland', 'Geneva', 'city', ['geneve']),
  international(
    'ho-chi-minh-city',
    'Ho Chi Minh City',
    'VN',
    'Vietnam',
    'Southeast Vietnam',
    'city',
    ['saigon'],
  ),
  international('interlaken', 'Interlaken', 'CH', 'Switzerland', 'Bern', 'mountains'),
  international('jeju-island', 'Jeju Island', 'KR', 'South Korea', 'Jeju', 'island', ['jeju']),
  international('kathmandu', 'Kathmandu', 'NP', 'Nepal', 'Bagmati', 'city'),
  international('kuala-lumpur', 'Kuala Lumpur', 'MY', 'Malaysia', 'Kuala Lumpur', 'city'),
  international('krabi', 'Krabi', 'TH', 'Thailand', 'Krabi', 'coast'),
  international('langkawi', 'Langkawi', 'MY', 'Malaysia', 'Kedah', 'island'),
  international('machu-picchu', 'Machu Picchu', 'PE', 'Peru', 'Cusco', 'heritage'),
  international('marrakech', 'Marrakech', 'MA', 'Morocco', 'Marrakesh-Safi', 'heritage', [
    'marrakesh',
  ]),
  international('muscat', 'Muscat', 'OM', 'Oman', 'Muscat', 'city'),
  international('petra', 'Petra', 'JO', 'Jordan', "Ma'an", 'heritage'),
  international('seychelles', 'Seychelles', 'SC', 'Seychelles', null, 'country'),
  international('siem-reap', 'Siem Reap', 'KH', 'Cambodia', 'Siem Reap', 'heritage'),
  international('tbilisi', 'Tbilisi', 'GE', 'Georgia', 'Tbilisi', 'city'),
  international('italy', 'Italy', 'IT', 'Italy', null, 'country'),
  international('united-states', 'United States', 'US', 'United States', null, 'country', [
    'united states of america',
    'usa',
  ]),
  international('china', 'China', 'CN', 'China', null, 'country'),
  international('japan', 'Japan', 'JP', 'Japan', null, 'country'),
  international('france', 'France', 'FR', 'France', null, 'country'),
  international('spain', 'Spain', 'ES', 'Spain', null, 'country'),
  international('thailand', 'Thailand', 'TH', 'Thailand', null, 'country'),
  international('indonesia', 'Indonesia', 'ID', 'Indonesia', null, 'country'),
  international('vietnam', 'Vietnam', 'VN', 'Vietnam', null, 'country'),
  international('australia', 'Australia', 'AU', 'Australia', null, 'country'),
  international('new-zealand', 'New Zealand', 'NZ', 'New Zealand', null, 'country'),
  international('switzerland', 'Switzerland', 'CH', 'Switzerland', null, 'country'),
  international('greece', 'Greece', 'GR', 'Greece', null, 'country'),
  international('turkiye', 'Türkiye', 'TR', 'Türkiye', null, 'country', ['turkey']),
  international(
    'united-arab-emirates',
    'United Arab Emirates',
    'AE',
    'United Arab Emirates',
    null,
    'country',
    ['uae'],
  ),
  international('united-kingdom', 'United Kingdom', 'GB', 'United Kingdom', null, 'country', [
    'britain',
    'great britain',
    'uk',
  ]),
  international('portugal', 'Portugal', 'PT', 'Portugal', null, 'country'),
  international('germany', 'Germany', 'DE', 'Germany', null, 'country'),
  international('austria', 'Austria', 'AT', 'Austria', null, 'country'),
  international('canada', 'Canada', 'CA', 'Canada', null, 'country'),
  international('south-korea', 'South Korea', 'KR', 'South Korea', null, 'country', [
    'republic of korea',
  ]),
  international('egypt', 'Egypt', 'EG', 'Egypt', null, 'country'),
  international('south-africa', 'South Africa', 'ZA', 'South Africa', null, 'country'),
  international('malaysia', 'Malaysia', 'MY', 'Malaysia', null, 'country'),
  international('nepal', 'Nepal', 'NP', 'Nepal', null, 'country'),
  international('sri-lanka', 'Sri Lanka', 'LK', 'Sri Lanka', null, 'country'),
];

export const initialDestinationCatalog = destinationCatalogSchema.parse([
  ...indiaDestinations,
  ...internationalDestinations,
]);

export const initialDestinationCatalogCounts = Object.freeze({
  india: indiaDestinations.length,
  international: internationalDestinations.length,
  total: indiaDestinations.length + internationalDestinations.length,
});
